"""empty message

Revision ID: 09214e23c933
Revises: f5b17bf88739
Create Date: 2024-10-07 17:53:35.043320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09214e23c933'
down_revision: Union[str, None] = 'f5b17bf88739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('products', sa.Column('product_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_picture')
    op.drop_column('customers', 'profile_picture')
    # ### end Alembic commands ###
